Characters/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('character/create/', views.CharacterCreate.as_view(), name='character_create'),
  path('character/', views.character_index, name='character'),
  path('character/<int:character_id>/', views.character_detail, name='detail'),
  path('character/<int:pk>/update/', views.CharacterUpdate.as_view(), name='character_update'),
  path('character/<int:pk>/delete/', views.CharacterDelete.as_view(), name='character_delete'),
  path('character/<int:character_id>/add_battle', views.add_battle,name='add_feeding'),
  path('character/<int:character_id>/unused_weapon/<int:weapon_id>/', views.unused_weapon,name='unused_weapon'),
  path('weapon/create/', views.WeaponCreate.as_view(), name='weapon_create'),
  path('weapon/', views.weapon_index, name='weapon'),
  path('weapon/<int:weapon_id>/', views.weapon_detail, name='weapon_detail'),
  path('weapon/<int:pk>/update/', views.WeaponUpdate.as_view(), name='weapon_update'),
  path('weapon/<int:pk>/delete/', views.WeaponDelete.as_view(), name='weapon_delete')
]

main_app/models.py
from datetime import datetime
from django.db import models
from django.urls import reverse

# Create your models here.


class Weapon(models.Model):
    name=models.CharField(max_length=100)
    description=models.CharField(max_length=250)
    type=models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('weapon_detail', kwargs={'weapon_id': self.id})
        
class Character(models.Model):
    name=models.CharField(max_length=100)
    description=models.CharField(max_length=250)
    status=models.CharField(max_length=100)
    power_level=models.IntegerField()
    weapons =models.ManyToManyField(Weapon)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'character_id': self.id})


class Battles(models.Model):
    class Meta:
        ordering =['-date']

    RESULTS=(
        ('W','Win'),
        ('L','Loss'),
        ('T','Tie'),
    )
    date=models.DateField('Battle Date')
    result=models.CharField(
        max_length=1, 
        choices=RESULTS, 
        default=RESULTS[0][0],
        )
    character = models.ForeignKey(Character, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_result_display()} on {self.date} "

main_app/forms.py
from django.forms import ModelForm
from .models import Battles


class BattlesForm(ModelForm):
    class Meta:
        model = Battles
        fields=['date','result']

    

main_app/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Character, Weapon
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import BattlesForm

# Create your views here.
def home(request):
    return render(request,'index.html')

def about(request):
    return render(request, 'about.html')

def character_index(request):
    characters = Character.objects.all()
    return render(request, 'character/index.html',{'characters':characters})

def character_detail(request,character_id):
    character= Character.objects.get(id=character_id)
    battles_form=BattlesForm()
    unused_wapons = Weapon.objects.exclude(id__in = character.weapons.all().values_list('id'))
    return render(request,'character/detail.html',{
        'character':character,
        'battles_form':battles_form,
        'weapons':unused_wapons,
        },)

def add_battle(request,character_id):
    form = BattlesForm(request.POST)
    if form.is_valid():
        new_Battle = form.save(commit=False)
        new_Battle.character_id=character_id
        new_Battle.save()
    return redirect('detail',character_id=character_id)

class CharacterCreate(CreateView):
    model=Character
    fields='__all__'
    # success_url='/character/'

class CharacterUpdate(UpdateView):
    model= Character
    fields=['description','status','power_level']

class CharacterDelete(DeleteView):
    model=Character
    success_url='/character/'



def weapon_index(request):
    weapons = Weapon.objects.all()
    return render(request, 'weapon/index.html',{'weapons':weapons})

def weapon_detail(request,weapon_id):
    weapon= Weapon.objects.get(id=weapon_id)
    return render(request,'weapon/detail.html',{'weapon':weapon})

def unused_weapon(request, character_id, weapon_id):
    Character.objects.get(id=character_id).weapons.add(weapon_id)
    return redirect('detail', character_id=character_id)

class WeaponCreate(CreateView):
    model=Weapon
    fields='__all__'

class WeaponUpdate(UpdateView):
    model=Weapon
    fields={'type','description'}

class WeaponDelete(DeleteView):
    model=Weapon
    success_url='/weapon/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
    <h1>About the Character</h1>
    <hr />
    <p>Get the best Characters</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
!<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Characters</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js" ></script>

        
    </head>
    <body>
        <header class="navbar-fixed">
          <nav>
            <div class="nav-wrapper">
              <ul>
                <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Character</a></li></ul>
                
              </ul>
              <ul class="right">
                <li><a href="/character">View All My Characters</a></li>
                <li><a href="/weapon">View All My Weapons</a></li>
                <li><a href="/about">About</a></li>
                <li><a href="{% url 'character_create' %}">Add a Character</a></li>
                <li><a href="{% url 'weapon_create' %}">Add a Weapon</a></li>
              </ul>
            </div>
          </nav>
        </header>
        <main class="container">
          {% block content %}
          {% endblock %}
        </main>
        <footer class="page-footer">
          <div class="right">All Rights Reserved, &copy; 2019 Character &nbsp;</div>
        </footer>
      </body>
</html>

main_app/templates/character/detail.html
{% extends 'base.html' %}
{% block content %}
<h1> Character Details</h1>
<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ character.name }}</span>
        <p>Power Level: {{ character.power_level }}</p>
        <p>Description: {{ character.description }}</p>
      </div>
      <div class="card-action">
          <a href="{% url 'character_update' character.id %}">Edit</a>
          <a href="{% url 'character_delete' character.id %}">Delete</a>
      </div>
  </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_feeding' character.id %}" method="POST">
      {% csrf_token %}
      {{ battles_form.as_p }}
      <input type="submit" class="btn" value="Add Battle">
    </form>
  </div>
  </div>
  <div class="row">
    <div class="col s12">
  
  <table class="striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Battle</th>
      </tr>
    </thead>
    <tbody>
      {% for battle in character.battles_set.all %}
      <tr>
        <td>{{battle.date}}</td>
        <td>{{ battle.get_result_display }}</td>
      </tr> 
      {% endfor %}
      <tr>
        
      </tr>
    </tbody>
    <tfoot>
      
    </tfoot>


  </table>
</div>
</div>

    <div class="row">
      <div class="col s6">
          <h3>Available Weapons</h3>
          {% if weapons.count %}
            {% for weapon in weapons.all %}
              <div class="card">
                <div class="card-content">
                  <span class="card-title">{{ weapon.name }}</span>
                  <p>Description: {{ weapon.description }}</p>
                  <p>Type: {{weapon.type}}</p>
                </div>
                <div class="card-action">
                  <form action="{% url 'unused_weapon' character.id weapon.id %}" method="POST">
                    {% csrf_token %}
                    <button class="btn" type="submit">Add</button>
                  </form>
                </div>  
              </div>
            {% endfor %}
          {% else %}  
            <h5>{{character.name}}, already has all available weapons.</h5>
          {% endif %}
      </div>
      <div class="col s6">
        <h3>{{character.name}}'s Weapons</h3>
        {% if character.weapons.count %}
          {% for weapon in character.weapons.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">{{ weapon.name }}</span>
              <p>Description: {{ weapon.description }}</p>
              <p>Type: {{weapon.type}}</p>
            </div>
          
        </div>
          {% endfor %}
        {% else %}  
          <h5>No Weapons</h5>
        {% endif %}
    </div>
    
    </div>
    <script>
      //configure datepicker
      const dateEl = document.getElementById('id_date');
      const selectEl= document.getElementById('id_result');
      
      M.Datepicker.init(dateEl,{
        format:'yyyy-mm-dd',
        default:new Date(),
        setDefault:true,
        autoClose:true,
      })
      M.FormSelect.init(selectEl)

      //configure the select tag
    </script>


{% endblock %}

main_app/templates/character/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Character List</h1>

{% for character in characters %}
  <div class="card">
    <a href="{% url 'detail' character.id %}">
    <div class="card-content">
      <span class="card-title">{{ character.name }}</span>
      <p>Power Level: {{ character.power_level }}</p>
      <p>Description: {{ character.description }}</p>
      
    </div>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/index.html
{% extends 'base.html' %}
{% block content %}

<h1>I Love Anime</h1>


{% endblock %}

main_app/templates/main_app/character_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Character</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' character.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/character_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
  <h1>Edit <span class='teal-text'>{{object.name}}</span></h1>
{% else %}
  <h1>Create Character</h1>
{% endif %}

  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/weapon_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Weapon</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'weapon_detail' weapon.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/weapon_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
  <h1>Edit <span class='teal-text'>{{object.name}}</span></h1>
{% else %}
  <h1>Create Weapon</h1>
{% endif %}

  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/weapon/detail.html
{% extends 'base.html' %}
{% block content %}
<h1> Weapon Details</h1>


  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ weapon.name }}</span>
      <p>Type: {{ weapon.type }}</p>
      <p>Description: {{ weapon.description }}</p>
    </div>
    <div class="card-action">
        <a href="{% url 'weapon_update' weapon.id %}">Edit</a>
        <a href="{% url 'weapon_delete' weapon.id %}">Delete</a>
    </div>
  </div>

{% endblock %}

main_app/templates/weapon/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Weapon List</h1>

{% for weapon in weapons %}
  <div class="card">
    <a href="{% url 'weapon_detail' weapon.id %}">
    <div class="card-content">
      <span class="card-title">{{ weapon.name }}</span>
      <p>Type: {{ weapon.type }}</p>
      <p>Description: {{ weapon.description }}</p>
      
    </div>
  </div>
{% endfor %}

{% endblock %}